name: Build and push a release image

on:
  push:
    tags:
      - v*

jobs:
  get-version:
    runs-on: [ubuntu-latest]
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Extract version from Github ref
        id: get-version
        env:
          TAG: ${{ github.ref }}
        run: |
          version=${TAG:10}
          echo "::set-output name=version::$version"
  build:
    runs-on: [ubuntu-latest]
    needs: get-version
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - uses: actions/checkout@v4
      - name: Build antrea-operator Docker image
        env:
          VERSION: ${{ needs.get-version.outputs.version }}
        run: |
          make docker-build

      - name: Push images to registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: ${{ needs.get-version.outputs.version }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push antrea/antrea-operator:"$VERSION"
