name: Certify container with OpenShift

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        default: 'latest'
      is_latest:
        description: 'Set as latest'
        required: true
        default: true
        type: boolean
jobs:
  validate_image:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Run container certification
        env:
          VERSION: ${{ github.event.inputs.version_tag }}
          IS_LATEST: ${{ github.event.inputs.is_latest }}
          OCP_PROJECT_NAMESPACE: ${{ secrets.OCP_PROJECT_NAMESPACE }}
          REGISTRY_LOGIN_USERNAME: ${{ secrets.REGISTRY_LOGIN_USERNAME }}
          REGISTRY_LOGIN_PASSWORD: ${{ secrets.REGISTRY_LOGIN_PASSWORD }}
          PFLT_PYXIS_API_TOKEN: ${{ secrets.PFLT_PYXIS_API_TOKEN }}
          PFLT_CERTIFICATION_PROJECT_ID: ${{ secrets.PFLT_CERTIFICATION_PROJECT_ID }}
        run: |
          ./hack/certify-operator-ocp.sh
