name: Go

on:
  pull_request:
    branches:
      - main

jobs:
  bin:
    name: Build binary and run unit tests
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Check-out code
        uses: actions/checkout@v4
      - name: Build antrea-operator binary
        run: make bin
      - name: Run tests
        run: make test

  check-tidy:
    name: Check tidy
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Check-out code
        uses: actions/checkout@v4
      - name: Check tidy
        run: make test-tidy
